name: "Build Extension .zip"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: cd extension && npm ci

      - name: Build
        run: cd extension && npm run build
      
      - name: Zip Extension
        run: |
          cd extension
          cp manifest.json popup.html popup.css dist/
          cp -r images dist/
          cd dist
          zip -rq ../../exterstellar-use-this-in-extensions-page.zip .

      - name: Set short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: exterstellar-${{env.SHORT_SHA}}-unzip
          path: exterstellar-use-this-in-extensions-page.zip